require "option_parser"

input_file = ""
output_file = ""

ARGV.delete("--") if ARGV.includes?("--")

parser = OptionParser.new do |p|
  p.banner = "Usage: export_song [options] [input_file output_file]"

  p.on("-i INPUT", "--input=INPUT", "Input .mod song file") { |f| input_file = f }
  p.on("-o OUTPUT", "--output=OUTPUT", "Output header file (.h)") { |f| output_file = f }

  p.on("-h", "--help", "Show help") do
    puts p
    exit
  end

  p.unknown_args do |positional|
    if input_file.empty? && positional.size > 0
      input_file = positional[0]
    end
    if output_file.empty? && positional.size > 1
      output_file = positional[1]
    end
  end
end

parser.parse

if input_file.empty? || output_file.empty?
  puts "Error: Both input and output file paths are required."
  puts parser
  exit 1
end

unless File.exists?(input_file)
  puts "Error: Input file '#{input_file}' not found."
  exit 1
end

bytes = File.read(input_file).to_slice

base_name = File.basename(input_file, File.extname(input_file))
var_name = base_name.downcase.gsub(/[^a-zA-Z0-9_]/, "_")

output_dir = File.dirname(output_file)
Dir.mkdir_p(output_dir) unless Dir.exists?(output_dir)

# String.build returns the built string directly
header_content = String.build do |str|
  str << "// Generated by export_song.cr\n"
  str << "#pragma once\n\n"
  str << "#include <cstddef>\n"
  str << "#include <cstdint>\n\n"
  str << "namespace Assets {\n"
  str << "    namespace Music {\n"
  str << "        inline const uint8_t #{var_name}_mod[] = {\n"

  bytes.each_with_index do |byte, index|
    str << "            " if index % 12 == 0
    str << sprintf("0x%02x", byte)
    str << ", " unless index == bytes.size - 1

    if (index + 1) % 12 == 0 || index == bytes.size - 1
      str << "\n"
    end
  end

  str << "        };\n"
  str << "        inline const size_t #{var_name}_mod_len = #{bytes.size};\n"
  str << "    }\n"
  str << "}\n"
end

# Write the string to file
File.write(output_file, header_content)

puts "Successfully exported '#{input_file}' -> '#{output_file}' (#{bytes.size} bytes)"