require "file_utils"
require "./export/font"
require "./export/music"
require "./export/image"

output_dir = "src/assets"
Dir.mkdir_p(output_dir) unless Dir.exists?(output_dir)

puts "==> Packing Game Assets..."

# -------------------------------------------------------------
# FONTS -> src/assets/Fonts.h
# -------------------------------------------------------------
font_files = Dir.glob("assets/fonts/*.txt")
if font_files.any?
  fonts_header = String.build do |str|
    str << "// Auto-generated by pack_assets.cr - DO NOT EDIT MANUALLY\n"
    str << "#pragma once\n\n"
    str << "#include \"core/Font.h\"\n\n"
    str << "namespace Assets {\n"
    str << "    namespace Fonts {\n\n"

    font_files.each do |file_path|
      puts "  [Font]  #{file_path}"
      str << FontExporter.export(file_path)
    end

    str << "    }\n"
    str << "}\n"
  end

  File.write(File.join(output_dir, "Fonts.h"), fonts_header)
  puts "Generated -> src/assets/Fonts.h"
end

# -------------------------------------------------------------
# IMAGES -> src/assets/Images.h
# -------------------------------------------------------------
image_files = Dir.glob("assets/images/*.aseprite")
if image_files.any?
  processed_sprites = [] of ImageExporter::SpriteData

  image_files.each do |file_path|
    puts "  [Image] #{file_path}"
    processed_sprites << ImageExporter.process_sprite(file_path)
  end

  images_header = String.build do |str|
    str << "// Auto-generated by pack_assets.cr - DO NOT EDIT MANUALLY\n"
    str << "#pragma once\n\n"
    str << "#include <cstddef>\n"
    str << "#include <cstdint>\n\n"
    str << "namespace Assets {\n"
    str << "    namespace Images {\n\n"

    # Export Global Palette (using palette from first sprite, padded to 256 colors)
    global_palette = processed_sprites.first.palette.dup
    while global_palette.size < 256
      global_palette << "0x00FF00FF" # Padding with magenta default transparency indicator
    end

    str << "        inline const uint32_t GLOBAL_PALETTE[256] = {\n"
    global_palette.each_slice(8) do |chunk|
      str << "            " << chunk.join(", ") << ",\n"
    end
    str << "        };\n\n"

    # Export individual RLE arrays
    processed_sprites.each do |sprite|
      str << "        inline const size_t #{sprite.name}_len = #{sprite.compressed_size};\n"
      str << "        inline const uint8_t #{sprite.name}[#{sprite.compressed_size}] = {\n"
      str << "            " << sprite.c_array_string << "\n"
      str << "        };\n\n"
    end

    str << "    }\n"
    str << "}\n"
  end

  File.write(File.join(output_dir, "Images.h"), images_header)
  puts "Generated -> src/assets/Images.h"
end

# -------------------------------------------------------------
# MUSIC -> src/assets/Music.h
# -------------------------------------------------------------
music_files = Dir.glob("assets/music/*.mod")
if music_files.any?
  music_header = String.build do |str|
    str << "// Auto-generated by pack_assets.cr - DO NOT EDIT MANUALLY\n"
    str << "#pragma once\n\n"
    str << "#include <cstddef>\n"
    str << "#include <cstdint>\n\n"
    str << "namespace Assets {\n"
    str << "    namespace Music {\n"

    music_files.each do |file_path|
      puts "  [Music] #{file_path}"
      str << MusicExporter.export(file_path)
    end

    str << "    }\n"
    str << "}\n"
  end

  File.write(File.join(output_dir, "Music.h"), music_header)
  puts "Generated -> src/assets/Music.h"
end

puts "==> All asset packs updated successfully!"
