require "file_utils"
require "./export/font"
require "./export/music"
require "./export/image"

output_dir = "src/assets"
Dir.mkdir_p(output_dir) unless Dir.exists?(output_dir)

# Parse optional filter flag (e.g. --only=fonts, --only=images, --only=music)
target_filter = nil
ARGV.each do |arg|
  if arg.starts_with?("--only=")
    target_filter = arg.split("=").last.downcase
  end
end

puts "==> Packing Game Assets#{target_filter ? " [Filter: #{target_filter}]" : ""}..."

# Helper check to see if a category should run
def should_run?(category : String, filter : String?)
  return true if filter.nil?
  filter == category.downcase
end

# -------------------------------------------------------------
# FONTS -> src/assets/Fonts.h
# -------------------------------------------------------------
if should_run?("fonts", target_filter)
  font_files = Dir.glob("assets/fonts/*.txt")
  if font_files.any?
    fonts_header = String.build do |str|
      str << "// Auto-generated by pack_assets.cr - DO NOT EDIT MANUALLY\n"
      str << "#pragma once\n\n"
      str << "#include \"core/Font.h\"\n\n"
      str << "namespace Assets {\n"
      str << "    namespace Fonts {\n\n"

      font_files.each do |file_path|
        puts "  [Font]  #{file_path}"
        str << FontExporter.export(file_path)
      end

      str << "    }\n"
      str << "}\n"
    end

    File.write(File.join(output_dir, "Fonts.h"), fonts_header)
    puts "Generated -> src/assets/Fonts.h"
  end
end

# -------------------------------------------------------------
# IMAGES -> src/assets/Images.h
# -------------------------------------------------------------
if should_run?("images", target_filter)
  image_files = Dir.glob("assets/images/*.aseprite")
  if image_files.any?
    processed_sprites = [] of ImageExporter::SpriteData

    image_files.each do |file_path|
      puts "  [Image] #{file_path}"
      processed_sprites << ImageExporter.process_sprite(file_path)
    end

    images_header = String.build do |str|
      str << "// Auto-generated by pack_assets.cr - DO NOT EDIT MANUALLY\n"
      str << "#pragma once\n\n"
      str << "#include <cstddef>\n"
      str << "#include <cstdint>\n\n"
      str << "namespace Assets {\n"
      str << "    namespace Images {\n\n"

      # Export Global Palette (using palette from first sprite, padded to 256 colors)
      global_palette = processed_sprites.first.palette.dup
      while global_palette.size < 256
        global_palette << "0x00FF00FF" # Padding with magenta default transparency indicator
      end

      str << "        inline const uint32_t GLOBAL_PALETTE[256] = {\n"
      global_palette.each_slice(8) do |chunk|
        str << "            " << chunk.join(", ") << ",\n"
      end
      str << "        };\n\n"

      # Export individual RLE arrays
      processed_sprites.each do |sprite|
        str << "        inline const size_t #{sprite.name}_len = #{sprite.compressed_size};\n"
        str << "        inline const uint8_t #{sprite.name}[#{sprite.compressed_size}] = {\n"
        str << "            " << sprite.c_array_string << "\n"
        str << "        };\n\n"
      end

      str << "    }\n"
      str << "}\n"
    end

    File.write(File.join(output_dir, "Images.h"), images_header)
    puts "Generated -> src/assets/Images.h"
  end
end

# -------------------------------------------------------------
# MUSIC -> src/assets/Music.h
# -------------------------------------------------------------
if should_run?("music", target_filter)
  music_files = Dir.glob("assets/music/*.mod")
  if music_files.any?
    music_header = String.build do |str|
      str << "// Auto-generated by pack_assets.cr - DO NOT EDIT MANUALLY\n"
      str << "#pragma once\n\n"
      str << "#include <cstddef>\n"
      str << "#include <cstdint>\n\n"
      str << "namespace Assets {\n"
      str << "    namespace Music {\n"

      music_files.each do |file_path|
        puts "  [Music] #{file_path}"
        str << MusicExporter.export(file_path)
      end

      str << "    }\n"
      str << "}\n"
    end

    File.write(File.join(output_dir, "Music.h"), music_header)
    puts "Generated -> src/assets/Music.h"
  end
end

puts "==> All asset packs updated successfully!"
